version: "2"
run:
  timeout: 5m
  concurrency: 14
issues:
  max-issues-per-linter: 500
  max-same-issues: 0
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    # - dupl
    # - dupword
    # - durationcheck
    # - errorlint
    - errchkjson
    - exhaustive
    # - forcetypeassert
    # - gochecknoglobals
    # - goconst
    # - gocritic
    # # - err113
    # - gofmt
    - goprintffuncname
    - gosec
    - grouper
    # - ireturn
    - loggercheck
    - makezero
    - misspell
    # # - musttag
    - nakedret
    # # - nestif
    - nilerr
    # - noctx
    - nonamedreturns
    - nosprintfhostport
    # - prealloc
    # - predeclared
    - promlinter
    - reassign
    - revive
    - sqlclosecheck
    # - stylecheck
    # - tagliatelle
    - testifylint
    - thelper
    # - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    # # - varnamelen
    - wastedassign
    - whitespace

  exclusions:
    generated: strict
    rules:
      - path: _test\.go
        linters:
          - gosec
      - path: services/users/mock/
        linters:
          - gosec
      - path: services/users/test/
        linters:
          - gosec
      - path: tools/cli
        linters:
          - gosec
        text: "G304"

  settings:
    gosec:
      excludes:
        - G104
        # - G304
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        # Common io.Closer implementations
        - (*os.File).Close
        - (io.ReadCloser).Close # Should cover http.Response.Body.Close and similar
        - (*database/sql.Rows).Close
        - (io/fs.File).Close # For embedded file system
        # Common Flushers
        - (*bufio.Writer).Flush
        - (*text/tabwriter.Writer).Flush # For CLI writers
        # Specific application types
        - (*go.opentelemetry.io/otel/sdk/metric.MeterProvider).ForceFlush # For telemetry meter
        - (*github.com/go-redis/redis/v8.PubSub).Close # For Redis PubSub
        - (*github.com/coder/websocket.Conn).Close # For Loki websocket connections
    reassign:
      # Patterns for global variable names that are checked for reassignment.
      # See https://github.com/curioswitch/go-reassign#usage
      # Default: ["EOF", "Err.*"]
      patterns:
        - ".*"
    revive:
      # Maximum number of open files at the same time.
      # See https://github.com/mgechev/revive#command-line-flags
      # Defaults to unlimited.
      max-open-files: 2048
      # Sets the default severity.
      # See https://github.com/mgechev/revive#configuration
      # Default: warning
      severity: error
      # Enable all available rules.
      # Default: false
      enable-all-rules: false
      # Sets the default failure confidence.
      # This means that linting errors with less than 0.8 confidence will be ignored.
      # Default: 0.8
      confidence: 0.8
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#add-constant
        - name: add-constant
          severity: warning
          disabled: true
          arguments:
            - maxLitCount: "3"
              allowStrs: '""'
              allowInts: "0,1,2"
              allowFloats: "0.0,0.,1.0,1.,2.0,2."
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#argument-limit
        - name: argument-limit
          severity: warning
          disabled: true
          arguments: [4]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#atomic
        - name: atomic
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#banned-characters
        - name: banned-characters
          severity: warning
          disabled: true
          arguments: ["Ω", "Σ", "σ", "7"]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#bare-return
        - name: bare-return
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#blank-imports
        - name: blank-imports
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#bool-literal-in-expr
        - name: bool-literal-in-expr
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#call-to-gc
        - name: call-to-gc
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#cognitive-complexity
        - name: cognitive-complexity
          severity: warning
          disabled: true
          arguments: [7]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#comment-spacings
        - name: comment-spacings
          severity: warning
          disabled: true
          arguments:
            - mypragma
            - otherpragma
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#confusing-naming
        - name: confusing-naming
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#confusing-results
        - name: confusing-results
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#constant-logical-expr
        - name: constant-logical-expr
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-as-argument
        - name: context-as-argument
          severity: warning
          disabled: false
          arguments:
            - allowTypesBefore: "*testing.T,*github.com/user/repo/testing.Harness"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-keys-type
        - name: context-keys-type
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#cyclomatic
        - name: cyclomatic
          severity: warning
          disabled: true
          arguments: [3]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#datarace
        - name: datarace
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#deep-exit
        - name: deep-exit
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#defer
        - name: defer
          severity: warning
          disabled: true
          arguments:
            - ["call-chain", "loop"]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
        - name: dot-imports
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#duplicated-imports
        - name: duplicated-imports
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#early-return
        - name: early-return
          severity: warning
          disabled: true
          arguments:
            - "preserveScope"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-block
        - name: empty-block
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-lines
        - name: empty-lines
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-naming
        - name: error-naming
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-return
        - name: error-return
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-strings
        - name: error-strings
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#errorf
        - name: errorf
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
        - name: exported
          severity: warning
          disabled: false
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#file-header
        - name: file-header
          severity: warning
          disabled: true
          arguments:
            - This is the text that must appear at the top of source files.
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#flag-parameter
        - name: flag-parameter
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#function-result-limit
        - name: function-result-limit
          severity: warning
          disabled: true
          arguments: [2]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#function-length
        - name: function-length
          severity: warning
          disabled: true
          arguments: [10, 0]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#get-return
        - name: get-return
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#identical-branches
        - name: identical-branches
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#if-return
        - name: if-return
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#increment-decrement
        - name: increment-decrement
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#indent-error-flow
        - name: indent-error-flow
          severity: warning
          disabled: true
          arguments:
            - "preserveScope"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#imports-blacklist
        - name: imports-blocklist
          severity: warning
          disabled: true
          arguments:
            - "crypto/md5"
            - "crypto/sha1"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#import-shadowing
        - name: import-shadowing
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#line-length-limit
        - name: line-length-limit
          severity: warning
          disabled: true
          arguments: [80]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#max-public-structs
        - name: max-public-structs
          severity: warning
          disabled: true
          arguments: [3]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#modifies-parameter
        - name: modifies-parameter
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#modifies-value-receiver
        - name: modifies-value-receiver
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#nested-structs
        - name: nested-structs
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#optimize-operands-order
        - name: optimize-operands-order
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#package-comments
        - name: package-comments
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range
        - name: range
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range-val-in-closure
        - name: range-val-in-closure
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range-val-address
        - name: range-val-address
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#receiver-naming
        - name: receiver-naming
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#redefines-builtin-id
        - name: redefines-builtin-id
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#string-of-int
        - name: string-of-int
          severity: warning
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#string-format
        - name: string-format
          severity: warning
          disabled: true
          arguments:
            - - 'core.WriteError[1].Message'
              - '/^([^A-Z]|$)/'
              - must not start with a capital letter
            - - 'fmt.Errorf[0]'
              - '/(^|[^\.!?])$/'
              - must not end in punctuation
            - - panic
              - '/^[^\n]*$/'
              - must not contain line breaks
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#struct-tag
        - name: struct-tag
          arguments:
            - "json,inline"
            - "bson,outline,gnu"
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#superfluous-else
        - name: superfluous-else
          severity: warning
          disabled: false
          arguments:
            - "preserveScope"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#time-equal
        - name: time-equal
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#time-naming
        - name: time-naming
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
        - name: var-naming
          severity: warning
          disabled: true
          arguments:
            - ["ID"] # AllowList
            - ["VM"] # DenyList
            - - upperCaseConst: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-declaration
        - name: var-declaration
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unconditional-recursion
        - name: unconditional-recursion
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-naming
        - name: unexported-naming
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-return
        - name: unexported-return
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unhandled-error
        - name: unhandled-error
          severity: warning
          disabled: false
          arguments:
            - "fmt\\.Printf"
            - "fmt\\.Println"
            - "fmt\\.Fprintf"
            - "fmt\\.Fprintln"
            - ".*\\.Close"
            - ".*\\.Flush"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unnecessary-stmt
        - name: unnecessary-stmt
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unreachable-code
        - name: unreachable-code
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          severity: warning
          disabled: false
          arguments:
            - allowRegex: "^_"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
        - name: unused-receiver
          severity: warning
          disabled: false
          arguments:
            - allowRegex: "^_"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#useless-break
        - name: useless-break
          severity: warning
          disabled: false
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#waitgroup-by-value
        - name: waitgroup-by-value
          severity: warning
          disabled: true
